site_name: dotoryeee's blog

theme:
  name: material
  logo: logo.svg
  font:
    text: Changa
  features:
    - content.code.copy
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.tabs.link
  palette:
    primary: deep orange

extra:
  homepage: https://dotoryeee.github.io
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gardengarden/
    - icon: fontawesome/brands/github
      link: https://github.com/dotoryeee
  analytics:
    provider: google
    property: G-22LC2P5RV5

copyright: Copyright &copy; 2025 Jeongwon(Aaron) Lee

plugins:
  - blog:
      blog_dir: blog
      post_date_format: medium
      post_excerpt_separator: <!-- more -->
      # post_excerpt: required
      archive_date_format: yyyy MMMM
      post_readtime_words_per_minute: 150
      archive_url_date_format: yyyy/MM
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      draft_on_serve: false
      draft: false
      

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
