site_name: dotoryeee's blog

theme:
  name: material
  logo: logo.svg
  font:
    text: Changa
  features:
    - content.code.copy
    - navigation.expand
    - navigation.top
    - navigation.footer
  palette:
    primary: deep orange

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gardengarden/
    - icon: fontawesome/brands/github
      link: https://github.com/dotoryeee
  analytics:
    provider: google
    property: G-22LC2P5RV5

copyright: Copyright &copy; 2023 Jeongwon Lee

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
