FROM python:3.11

WORKDIR /comment_server

COPY ./comment_server /comment_server

RUN pip install -r requirements.txt

CMD ["uvicorn", "comment_server.main:app", "--host", "0.0.0.0", "--port", "8001"]
