FROM python:3.11

WORKDIR /comments

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./comments /comments

CMD ["uvicorn", "comments.main:app", "--host", "0.0.0.0", "--port", "8001"]
